version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/python
      
jobs:
  run-my-test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          python -m pip install --upgrade pip
          pip install unittest
          python app.py
          python test_frontend.py
          python test_api.py

workflows:
  my-custom-workflow:
    jobs:
      - run-my-test